name: Auto Release PECU

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    name: Crear GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Instalar dependencias
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg-dev

      - name: Obtener número de versión
        id: version
        run: |
          VERSION=$(date +'%Y.%m.%d')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "VERSION=$VERSION"  # Debugging

      - name: Empaquetar script en tar.gz
        run: |
          mkdir PECU-${{ env.VERSION }}
          cp proxmox-configurator.sh PECU-${{ env.VERSION }}/
          tar -czvf PECU-${{ env.VERSION }}.tar.gz PECU-${{ env.VERSION }}

      - name: Crear paquete Debian (.deb)
        run: |
          mkdir -p pecu-${{ env.VERSION }}/DEBIAN
          echo "Package: PECU" > pecu-${{ env.VERSION }}/DEBIAN/control
          echo "Version: ${{ env.VERSION }}" >> pecu-${{ env.VERSION }}/DEBIAN/control
          echo "Architecture: all" >> pecu-${{ env.VERSION }}/DEBIAN/control
          echo "Maintainer: Danilop95" >> pecu-${{ env.VERSION }}/DEBIAN/control
          echo "Description: Proxmox Enhanced Configuration Utility" >> pecu-${{ env.VERSION }}/DEBIAN/control
          mkdir -p pecu-${{ env.VERSION }}/usr/local/bin/
          cp proxmox-configurator.sh pecu-${{ env.VERSION }}/usr/local/bin/pecu
          chmod +x pecu-${{ env.VERSION }}/usr/local/bin/pecu
          dpkg-deb --build pecu-${{ env.VERSION }} pecu-${{ env.VERSION }}.deb

      - name: Crear GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: "Release v${{ env.VERSION }}"
          body: |
            ### What's New in This Update

            This update brings several improvements and bug fixes to enhance the performance and reliability of the Proxmox Enhanced Configuration Utility (PECU). Detailed changes include performance optimizations and improved error handling for a smoother experience.

            ### How to Update

            To update your PECU installation, follow one of these methods:

            **Direct Execution:**  
            Run the latest version of the script directly from GitHub by executing:
            ```bash
            bash <(curl -sL https://raw.githubusercontent.com/Danilop95/Proxmox-Enhanced-Configuration-Utility/refs/heads/main/proxmox-configurator.sh)
            ```

            **Local Installation:**  
            Clone the repository, set the proper permissions, and run the script locally:
            ```bash
            git clone https://github.com/Danilop95/Proxmox-Enhanced-Configuration-Utility.git
            cd Proxmox-Enhanced-Configuration-Utility
            chmod +x proxmox-configurator.sh
            sudo ./proxmox-configurator.sh
            ```

            ### Support the Project

            If you enjoy using PECU and would like to see it continue to improve, consider making a donation. Your support helps maintain and expand this project. Thank you!
          draft: false
          prerelease: false
          files: |
            PECU-${{ env.VERSION }}.tar.gz
            pecu-${{ env.VERSION }}.deb
