name: Auto Release PECU

on:
  push:
    branches:
      - testing
  workflow_dispatch:

jobs:
  release:
    name: Crear GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Instalar dependencias
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg-dev

      - name: Obtener número de versión
        id: version
        run: |
          VERSION=$(date +'%Y.%m.%d')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "VERSION=$VERSION"  # Debugging

      - name: Empaquetar script en tar.gz
        run: |
          mkdir PECU-${{ env.VERSION }}
          cp proxmox-configurator.sh PECU-${{ env.VERSION }}/
          tar -czvf PECU-${{ env.VERSION }}.tar.gz PECU-${{ env.VERSION }}

      - name: Crear o actualizar GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: "Release v${{ env.VERSION }}"
          update: true
          body: |
            ### What's New in This Update

            This update brings several improvements and bug fixes to enhance the performance and reliability of the Proxmox Enhanced Configuration Utility (PECU). Detailed changes include performance optimizations and improved error handling for a smoother experience.

            ### How to Update

            You can update your PECU installation by using the source code provided in this release. There are two ways to run this version:

            **Direct Execution (Latest Version):**  
            Run the script directly from GitHub using this command:
            ```bash
            bash <(curl -sL https://raw.githubusercontent.com/Danilop95/Proxmox-Enhanced-Configuration-Utility/v${{ env.VERSION }}/proxmox-configurator.sh)
            ```
            This command fetches and executes the specific version (v${{ env.VERSION }}) of the script.

            **Local Installation:**  
            Alternatively, you can download the source code archive (tar.gz) from the release assets and run the script locally:
            1. Download the archive.
            2. Extract the archive:
               ```bash
               tar -xzvf PECU-${{ env.VERSION }}.tar.gz
               ```
            3. Change to the extracted directory and run the script:
               ```bash
               cd PECU-${{ env.VERSION }}
               chmod +x proxmox-configurator.sh
               sudo ./proxmox-configurator.sh
               ```

            ### Important Note

            This release is a test release — it's the first time we're implementing automated releases. We apologize for any inconvenience caused by this initial notification. We are working to improve the release process for future versions.

            ### Support the Project

            If you enjoy using PECU and would like to see it continue to improve, consider making a donation. Your support helps maintain and expand this project. Thank you!

            Best regards,  
            Danilop95
          draft: false
          prerelease: false
          files: |
            PECU-${{ env.VERSION }}.tar.gz
