name: Auto Release PECU

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    name: Crear GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      releases: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Instalar dependencias
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg-dev

      - name: Obtener número de versión
        id: version
        run: |
          VERSION=$(date +'%Y.%m.%d')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "VERSION=$VERSION"  # Debugging

      - name: Empaquetar script en tar.gz
        run: |
          mkdir PECU-${{ env.VERSION }}
          cp proxmox-configurator.sh PECU-${{ env.VERSION }}/
          tar -czvf PECU-${{ env.VERSION }}.tar.gz PECU-${{ env.VERSION }}

      - name: Crear paquete Debian (.deb)
        run: |
          mkdir -p pecu-${{ env.VERSION }}/DEBIAN
          echo "Package: PECU" > pecu-${{ env.VERSION }}/DEBIAN/control
          echo "Version: ${{ env.VERSION }}" >> pecu-${{ env.VERSION }}/DEBIAN/control
          echo "Architecture: all" >> pecu-${{ env.VERSION }}/DEBIAN/control
          echo "Maintainer: Danilop95" >> pecu-${{ env.VERSION }}/DEBIAN/control
          echo "Description: Proxmox Enhanced Configuration Utility" >> pecu-${{ env.VERSION }}/DEBIAN/control
          mkdir -p pecu-${{ env.VERSION }}/usr/local/bin/
          cp proxmox-configurator.sh pecu-${{ env.VERSION }}/usr/local/bin/pecu
          chmod +x pecu-${{ env.VERSION }}/usr/local/bin/pecu
          dpkg-deb --build pecu-${{ env.VERSION }} pecu-${{ env.VERSION }}.deb

      - name: Crear GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: "Release v${{ env.VERSION }}"
          body: "Automated release of PECU for Proxmox."
          draft: false
          prerelease: false
          files: |
            PECU-${{ env.VERSION }}.tar.gz
            pecu-${{ env.VERSION }}.deb
